

# BEGIN_KITTY_FONTS
font_family      family="Ioskeley Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11
# END_KITTY_FONTS

term xterm-256color

disable_ligatures always

# include ./onedark.conf
# include ./kanagawa.conf
# include ./everforest.conf
# include ./frappe.conf
include ./gruvbox-dark.conf

map cmd+c           copy_to_clipboard
map cmd+v           paste_from_clipboard
map shift+insert    paste_from_clipboard

update_check_interval 24

allow_remote_control socket-only
listen_on unix:/tmp/kitty
shell_integration enabled

copy_on_select yes
active_tab_foreground   #d5e092

mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '/home/keb/.local/share/kebvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output

# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

